<a href="https://colab.research.google.com/github/aycakrk/DI725_Ayca/blob/main/Final_Project/phase3_qlora.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!unzip "/content/drive/MyDrive/RISCM.zip" -d "/content"

Streaming output truncated to the last 5000 lines.
  inflating: /content/resized/NWPU_1168.jpg
  inflating: /content/resized/RSICD_4364.jpg
  inflating: /content/resized/NWPU_18440.jpg
  inflating: /content/resized/NWPU_129.jpg
  inflating: /content/resized/NWPU_19322.jpg
  inflating: /content/resized/RSICD_3101.jpg
  inflating: /content/resized/UCM_2077.jpg
  inflating: /content/resized/NWPU_10992.jpg
  inflating: /content/resized/NWPU_10941.jpg
  inflating: /content/resized/NWPU_19048.jpg
  inflating: /content/resized/UCM_1535.jpg
  inflating: /content/resized/NWPU_22896.jpg
  inflating: /content/resized/NWPU_15332.jpg
  inflating: /content/resized/RSICD_7475.jpg
  inflating: /content/resized/NWPU_24431.jpg
  inflating: /content/resized/NWPU_25180.jpg
  inflating: /content/resized/RSICD_1536.jpg
  inflating: /content/resized/NWPU_18103.jpg
  inflating: /content/resized/NWPU_906.jpg
  inflating: /content/resized/NWPU_11526.jpg
  inflating: /content/resized/NWPU_22481.jpg
  inflating: /content/resized/NWPU_29001.jpg
  inflating: /content/resized/NWPU_18207.jpg
  inflating: /content/resized/NWPU_26448.jpg
  inflating: /content/resized/NWPU_7193.jpg
  inflating: /content/resized/UCM_288.jpg
  inflating: /content/resized/RSICD_10430.jpg
  inflating: /content/resized/NWPU_31285.jpg
  inflating: /content/resized/NWPU_21951.jpg
  inflating: /content/resized/RSICD_5686.jpg
  inflating: /content/resized/NWPU_1298.jpg
  inflating: /content/resized/RSICD_9561.jpg
  inflating: /content/resized/NWPU_4868.jpg
  inflating: /content/resized/NWPU_10956.jpg
  inflating: /content/resized/RSICD_6272.jpg
  inflating: /content/resized/RSICD_9942.jpg
  inflating: /content/resized/NWPU_17140.jpg
  inflating: /content/resized/NWPU_14786.jpg
  inflating: /content/resized/NWPU_28237.jpg
  inflating: /content/resized/NWPU_15480.jpg
  inflating: /content/resized/NWPU_27494.jpg
  inflating: /content/resized/NWPU_6966.jpg
  inflating: /content/resized/NWPU_18890.jpg
  inflating: /content/resized/NWPU_4792.jpg
  inflating: /content/resized/RSICD_417.jpg
  inflating: /content/resized/RSICD_9872.jpg
  inflating: /content/resized/RSICD_9578.jpg
  inflating: /content/resized/RSICD_9516.jpg
  inflating: /content/resized/RSICD_9913.jpg
  inflating: /content/resized/NWPU_8339.jpg
  inflating: /content/resized/NWPU_21620.jpg
  inflating: /content/resized/NWPU_2236.jpg
  inflating: /content/resized/NWPU_17696.jpg
  inflating: /content/resized/NWPU_30389.jpg
  inflating: /content/resized/NWPU_5276.jpg
  inflating: /content/resized/NWPU_6829.jpg
  inflating: /content/resized/NWPU_25384.jpg
  inflating: /content/resized/RSICD_9934.jpg
  inflating: /content/resized/RSICD_5577.jpg
  inflating: /content/resized/NWPU_30476.jpg
  inflating: /content/resized/RSICD_5722.jpg
  inflating: /content/resized/NWPU_4786.jpg
  inflating: /content/resized/NWPU_8508.jpg
  inflating: /content/resized/RSICD_10011.jpg
  inflating: /content/resized/NWPU_5773.jpg
  inflating: /content/resized/NWPU_27002.jpg
  inflating: /content/resized/RSICD_4459.jpg
  inflating: /content/resized/RSICD_9210.jpg
  inflating: /content/resized/RSICD_10801.jpg
  inflating: /content/resized/RSICD_4150.jpg
  inflating: /content/resized/RSICD_7247.jpg
  inflating: /content/resized/RSICD_6077.jpg
  inflating: /content/resized/UCM_307.jpg
  inflating: /content/resized/NWPU_29550.jpg
  inflating: /content/resized/RSICD_3063.jpg
  inflating: /content/resized/RSICD_611.jpg
  inflating: /content/resized/NWPU_19435.jpg
  inflating: /content/resized/UCM_1620.jpg
  inflating: /content/resized/RSICD_1302.jpg
  inflating: /content/resized/NWPU_21231.jpg
  inflating: /content/resized/RSICD_6095.jpg
  inflating: /content/resized/NWPU_16018.jpg
  inflating: /content/resized/NWPU_23697.jpg
  inflating: /content/resized/NWPU_14930.jpg
  inflating: /content/resized/RSICD_3926.jpg
  inflating: /content/resized/NWPU_16453.jpg
  inflating: /content/resized/RSICD_665.jpg
  inflating: /content/resized/RSICD_3912.jpg
  inflating: /content/resized/NWPU_29067.jpg
  inflating: /content/resized/NWPU_26863.jpg
  inflating: /content/resized/UCM_1061.jpg
  inflating: /content/resized/NWPU_19156.jpg
  inflating: /content/resized/NWPU_15935.jpg
  inflating: /content/resized/NWPU_3294.jpg
  inflating: /content/resized/NWPU_2029.jpg
  inflating: /content/resized/NWPU_30335.jpg
  inflating: /content/resized/NWPU_27088.jpg
  inflating: /content/resized/NWPU_1403.jpg
  inflating: /content/resized/NWPU_13506.jpg
  inflating: /content/resized/NWPU_3708.jpg
  inflating: /content/resized/RSICD_9014.jpg
  inflating: /content/resized/NWPU_30369.jpg
  inflating: /content/resized/NWPU_20978.jpg
  inflating: /content/resized/NWPU_18722.jpg
  inflating: /content/resized/RSICD_2219.jpg
  inflating: /content/resized/NWPU_18465.jpg
  inflating: /content/resized/RSICD_7240.jpg
  inflating: /content/resized/NWPU_192.jpg
  inflating: /content/resized/NWPU_5896.jpg
  inflating: /content/resized/NWPU_11270.jpg
  inflating: /content/resized/RSICD_6984.jpg
  inflating: /content/resized/NWPU_12745.jpg
  inflating: /content/resized/NWPU_31425.jpg
  inflating: /content/resized/NWPU_20243.jpg
  inflating: /content/resized/RSICD_6321.jpg
  inflating: /content/resized/RSICD_2379.jpg
  inflating: /content/resized/RSICD_6541.jpg
  inflating: /content/resized/NWPU_3025.jpg
  inflating: /content/resized/RSICD_7162.jpg
  inflating: /content/resized/NWPU_24427.jpg
  inflating: /content/resized/NWPU_8769.jpg
  inflating: /content/resized/UCM_1907.jpg
  inflating: /content/resized/NWPU_4598.jpg
  inflating: /content/resized/NWPU_21982.jpg
  inflating: /content/resized/NWPU_15220.jpg
  inflating: /content/resized/RSICD_5094.jpg
  inflating: /content/resized/NWPU_18809.jpg
  inflating: /content/resized/NWPU_25165.jpg
  inflating: /content/resized/RSICD_974.jpg
  inflating: /content/resized/RSICD_8942.jpg
  inflating: /content/resized/NWPU_25736.jpg
  inflating: /content/resized/NWPU_15321.jpg
  inflating: /content/resized/NWPU_24833.jpg
  inflating: /content/resized/NWPU_21126.jpg
  inflating: /content/resized/NWPU_30705.jpg
  inflating: /content/resized/NWPU_16409.jpg
  inflating: /content/resized/NWPU_16495.jpg
  inflating: /content/resized/RSICD_8725.jpg
  inflating: /content/resized/NWPU_23186.jpg
  inflating: /content/resized/RSICD_8634.jpg
  inflating: /content/resized/RSICD_1272.jpg
  inflating: /content/resized/NWPU_26392.jpg
  inflating: /content/resized/RSICD_1847.jpg
  inflating: /content/resized/NWPU_16198.jpg
  inflating: /content/resized/RSICD_7204.jpg
  inflating: /content/resized/NWPU_30266.jpg
  inflating: /content/resized/NWPU_2845.jpg
  inflating: /content/resized/NWPU_8901.jpg
  inflating: /content/resized/UCM_396.jpg
  inflating: /content/resized/NWPU_782.jpg
  inflating: /content/resized/RSICD_3132.jpg
  inflating: /content/resized/NWPU_26524.jpg
  inflating: /content/resized/NWPU_15418.jpg
  inflating: /content/resized/RSICD_8837.jpg
  inflating: /content/resized/NWPU_4385.jpg
  inflating: /content/resized/NWPU_15358.jpg
  inflating: /content/resized/NWPU_29083.jpg
  inflating: /content/resized/NWPU_26821.jpg
  inflating: /content/resized/RSICD_2396.jpg
  inflating: /content/resized/NWPU_22366.jpg
  inflating: /content/resized/NWPU_24110.jpg
  inflating: /content/resized/NWPU_9347.jpg
  inflating: /content/resized/NWPU_7846.jpg
  inflating: /content/resized/NWPU_19934.jpg
  inflating: /content/resized/NWPU_16678.jpg
  inflating: /content/resized/NWPU_15723.jpg
  inflating: /content/resized/NWPU_11431.jpg
  inflating: /content/resized/NWPU_21692.jpg
  inflating: /content/resized/RSICD_5706.jpg
  inflating: /content/resized/NWPU_14660.jpg
  inflating: /content/resized/NWPU_28773.jpg
  inflating: /content/resized/RSICD_6921.jpg
  inflating: /content/resized/NWPU_12073.jpg
  inflating: /content/resized/RSICD_3753.jpg
  inflating: /content/resized/NWPU_20011.jpg
  inflating: /content/resized/UCM_173.jpg
  inflating: /content/resized/NWPU_3226.jpg
  inflating: /content/resized/UCM_825.jpg
  inflating: /content/resized/NWPU_18106.jpg
  inflating: /content/resized/NWPU_24248.jpg
  inflating: /content/resized/NWPU_3372.jpg
  inflating: /content/resized/NWPU_14054.jpg
  inflating: /content/resized/NWPU_26081.jpg
  inflating: /content/resized/NWPU_3740.jpg
  inflating: /content/resized/NWPU_23109.jpg
  inflating: /content/resized/NWPU_2608.jpg
  inflating: /content/resized/NWPU_20456.jpg
  inflating: /content/resized/RSICD_10007.jpg
  inflating: /content/resized/NWPU_8766.jpg
  inflating: /content/resized/NWPU_8238.jpg
  inflating: /content/resized/RSICD_8507.jpg
  inflating: /content/resized/NWPU_17861.jpg
  inflating: /content/resized/RSICD_10012.jpg
  inflating: /content/resized/NWPU_5036.jpg
  inflating: /content/resized/NWPU_7693.jpg
  inflating: /content/resized/NWPU_28452.jpg
  inflating: /content/resized/NWPU_20447.jpg
  inflating: /content/resized/NWPU_12543.jpg
  inflating: /content/resized/RSICD_10385.jpg
  inflating: /content/resized/NWPU_27076.jpg
  inflating: /content/resized/NWPU_12867.jpg
  inflating: /content/resized/NWPU_23311.jpg
  inflating: /content/resized/NWPU_20630.jpg
  inflating: /content/resized/NWPU_30613.jpg
  inflating: /content/resized/NWPU_17530.jpg
  inflating: /content/resized/NWPU_21799.jpg
  inflating: /content/resized/NWPU_6357.jpg
  inflating: /content/resized/NWPU_5789.jpg
  inflating: /content/resized/NWPU_36.jpg
  inflating: /content/resized/NWPU_20953.jpg
  inflating: /content/resized/NWPU_23974.jpg
  inflating: /content/resized/RSICD_3992.jpg
  inflating: /content/resized/NWPU_29895.jpg
  inflating: /content/resized/NWPU_11772.jpg
  inflating: /content/resized/NWPU_11395.jpg
  inflating: /content/resized/RSICD_10015.jpg
  inflating: /content/resized/NWPU_14952.jpg
  inflating: /content/resized/RSICD_1809.jpg
  inflating: /content/resized/RSICD_9645.jpg
  inflating: /content/resized/NWPU_6204.jpg
  inflating: /content/resized/NWPU_12957.jpg
  inflating: /content/resized/NWPU_14615.jpg
  inflating: /content/resized/NWPU_21869.jpg
  inflating: /content/resized/RSICD_1982.jpg
  inflating: /content/resized/UCM_356.jpg
  inflating: /content/resized/RSICD_327.jpg
  inflating: /content/resized/RSICD_7239.jpg
  inflating: /content/resized/NWPU_9456.jpg
  inflating: /content/resized/NWPU_29376.jpg
  inflating: /content/resized/RSICD_10858.jpg
  inflating: /content/resized/NWPU_9722.jpg
  inflating: /content/resized/RSICD_5544.jpg
  inflating: /content/resized/NWPU_4469.jpg
  inflating: /content/resized/NWPU_23728.jpg
  inflating: /content/resized/NWPU_28543.jpg
  inflating: /content/resized/NWPU_20976.jpg
  inflating: /content/resized/NWPU_20215.jpg
  inflating: /content/resized/NWPU_14101.jpg
  inflating: /content/resized/NWPU_705.jpg
  inflating: /content/resized/NWPU_22136.jpg
  inflating: /content/resized/RSICD_7256.jpg
  inflating: /content/resized/RSICD_9864.jpg
  inflating: /content/resized/NWPU_13140.jpg
  inflating: /content/resized/NWPU_19929.jpg
  inflating: /content/resized/NWPU_24681.jpg
  inflating: /content/resized/RSICD_8116.jpg
  inflating: /content/resized/NWPU_4120.jpg
  inflating: /content/resized/NWPU_5166.jpg
  inflating: /content/resized/NWPU_29839.jpg
  inflating: /content/resized/NWPU_27049.jpg
  inflating: /content/resized/NWPU_2789.jpg
  inflating: /content/resized/NWPU_10198.jpg
  inflating: /content/resized/RSICD_1606.jpg
  inflating: /content/resized/NWPU_29058.jpg
  inflating: /content/resized/NWPU_16727.jpg
  inflating: /content/resized/NWPU_12935.jpg
  inflating: /content/resized/NWPU_30706.jpg
  inflating: /content/resized/NWPU_27549.jpg
  inflating: /content/resized/RSICD_9632.jpg
  inflating: /content/resized/NWPU_27535.jpg
  inflating: /content/resized/NWPU_18761.jpg
  inflating: /content/resized/NWPU_24388.jpg
  inflating: /content/resized/NWPU_19506.jpg
  inflating: /content/resized/RSICD_10668.jpg
  inflating: /content/resized/NWPU_2106.jpg
  inflating: /content/resized/NWPU_8495.jpg
  inflating: /content/resized/NWPU_24380.jpg
  inflating: /content/resized/RSICD_7269.jpg
  inflating: /content/resized/NWPU_3266.jpg
  inflating: /content/resized/UCM_897.jpg
  inflating: /content/resized/RSICD_9811.jpg
  inflating: /content/resized/NWPU_12049.jpg
  inflating: /content/resized/NWPU_2513.jpg
  inflating: /content/resized/RSICD_10114.jpg
  inflating: /content/resized/NWPU_12578.jpg
  inflating: /content/resized/NWPU_22832.jpg
  inflating: /content/resized/UCM_1481.jpg
  inflating: /content/resized/NWPU_1794.jpg
  inflating: /content/resized/NWPU_30264.jpg
  inflating: /content/resized/NWPU_21769.jpg
  inflating: /content/resized/NWPU_12913.jpg
  inflating: /content/resized/RSICD_1222.jpg
  inflating: /content/resized/NWPU_20465.jpg
  inflating: /content/resized/NWPU_8081.jpg
  inflating: /content/resized/NWPU_13295.jpg
  inflating: /content/resized/NWPU_2074.jpg
  inflating: /content/resized/NWPU_19571.jpg
  inflating: /content/resized/RSICD_8209.jpg
  inflating: /content/resized/NWPU_6962.jpg
  inflating: /content/resized/RSICD_7128.jpg
  inflating: /content/resized/NWPU_1331.jpg
  inflating: /content/resized/RSICD_7437.jpg
  inflating: /content/resized/RSICD_3744.jpg
  inflating: /content/resized/NWPU_27087.jpg
  inflating: /content/resized/UCM_248.jpg
  inflating: /content/resized/RSICD_3779.jpg
  inflating: /content/resized/NWPU_17207.jpg
  inflating: /content/resized/NWPU_12257.jpg
  inflating: /content/resized/NWPU_12415.jpg
  inflating: /content/resized/NWPU_23130.jpg
  inflating: /content/resized/NWPU_23959.jpg
  inflating: /content/resized/NWPU_11040.jpg
  inflating: /content/resized/RSICD_2010.jpg
  inflating: /content/resized/RSICD_3742.jpg
  inflating: /content/resized/NWPU_21178.jpg
  inflating: /content/resized/RSICD_2341.jpg
  inflating: /content/resized/RSICD_5064.jpg
  inflating: /content/resized/NWPU_16449.jpg
  inflating: /content/resized/UCM_1519.jpg
  inflating: /content/resized/NWPU_31336.jpg
  inflating: /content/resized/NWPU_5311.jpg
  inflating: /content/resized/NWPU_27214.jpg
  inflating: /content/resized/NWPU_12448.jpg
  inflating: /content/resized/RSICD_2479.jpg
  inflating: /content/resized/RSICD_2881.jpg
  inflating: /content/resized/NWPU_23168.jpg
  inflating: /content/resized/UCM_87.jpg
  inflating: /content/resized/RSICD_8758.jpg
  inflating: /content/resized/UCM_1429.jpg
  inflating: /content/resized/RSICD_7984.jpg
  inflating: /content/resized/NWPU_23185.jpg
  inflating: /content/resized/NWPU_19604.jpg
  inflating: /content/resized/NWPU_1602.jpg
  inflating: /content/resized/RSICD_691.jpg
  inflating: /content/resized/NWPU_28340.jpg
  inflating: /content/resized/NWPU_9760.jpg
  inflating: /content/resized/UCM_1225.jpg
  inflating: /content/resized/NWPU_15684.jpg
  inflating: /content/resized/NWPU_1841.jpg
  inflating: /content/resized/NWPU_1716.jpg
  inflating: /content/resized/NWPU_8666.jpg
  inflating: /content/resized/UCM_36.jpg
  inflating: /content/resized/NWPU_31404.jpg
  inflating: /content/resized/NWPU_5780.jpg
  inflating: /content/resized/NWPU_3102.jpg
  inflating: /content/resized/NWPU_29529.jpg
  inflating: /content/resized/NWPU_28117.jpg
  inflating: /content/resized/NWPU_27472.jpg
  inflating: /content/resized/NWPU_21880.jpg
  inflating: /content/resized/NWPU_1383.jpg
  inflating: /content/resized/NWPU_15960.jpg
  inflating: /content/resized/UCM_1159.jpg
  inflating: /content/resized/NWPU_27197.jpg
  inflating: /content/resized/NWPU_21168.jpg
  inflating: /content/resized/NWPU_15992.jpg
  inflating: /content/resized/NWPU_5569.jpg
  inflating: /content/resized/UCM_819.jpg
  inflating: /content/resized/NWPU_15344.jpg
  inflating: /content/resized/RSICD_492.jpg
  inflating: /content/resized/NWPU_26890.jpg
  inflating: /content/resized/NWPU_8559.jpg
  inflating: /content/resized/NWPU_24596.jpg
  inflating: /content/resized/NWPU_9786.jpg
  inflating: /content/resized/NWPU_1482.jpg
  inflating: /content/resized/NWPU_19381.jpg
  inflating: /content/resized/NWPU_30134.jpg
  inflating: /content/resized/NWPU_20426.jpg
  inflating: /content/resized/RSICD_3026.jpg
  inflating: /content/resized/NWPU_29088.jpg
  inflating: /content/resized/NWPU_30665.jpg
  inflating: /content/resized/NWPU_8627.jpg
  inflating: /content/resized/NWPU_25773.jpg
  inflating: /content/resized/NWPU_8528.jpg
  inflating: /content/resized/NWPU_26541.jpg
  inflating: /content/resized/NWPU_30583.jpg
  inflating: /content/resized/NWPU_16476.jpg
  inflating: /content/resized/NWPU_19211.jpg
  inflating: /content/resized/NWPU_9304.jpg
  inflating: /content/resized/RSICD_8611.jpg
  inflating: /content/resized/NWPU_24714.jpg
  inflating: /content/resized/UCM_2001.jpg
  inflating: /content/resized/RSICD_1027.jpg
  inflating: /content/resized/NWPU_2382.jpg
  inflating: /content/resized/NWPU_25383.jpg
  inflating: /content/resized/NWPU_21059.jpg
  inflating: /content/resized/NWPU_11412.jpg
  inflating: /content/resized/UCM_198.jpg
  inflating: /content/resized/NWPU_15629.jpg
  inflating: /content/resized/NWPU_24173.jpg
  inflating: /content/resized/NWPU_25358.jpg
  inflating: /content/resized/RSICD_8759.jpg
  inflating: /content/resized/RSICD_8043.jpg
  inflating: /content/resized/RSICD_9175.jpg
  inflating: /content/resized/NWPU_14381.jpg
  inflating: /content/resized/NWPU_3911.jpg
  inflating: /content/resized/RSICD_3627.jpg
  inflating: /content/resized/RSICD_9572.jpg
  inflating: /content/resized/UCM_1373.jpg
  inflating: /content/resized/RSICD_10842.jpg
  inflating: /content/resized/NWPU_27538.jpg
  inflating: /content/resized/NWPU_24762.jpg
  inflating: /content/resized/RSICD_10625.jpg
  inflating: /content/resized/NWPU_19814.jpg
  inflating: /content/resized/NWPU_6226.jpg
  inflating: /content/resized/NWPU_17757.jpg
  inflating: /content/resized/NWPU_12828.jpg
  inflating: /content/resized/RSICD_2784.jpg
  inflating: /content/resized/NWPU_14502.jpg
  inflating: /content/resized/NWPU_13706.jpg
  inflating: /content/resized/NWPU_25988.jpg
  inflating: /content/resized/RSICD_8570.jpg
  inflating: /content/resized/NWPU_30280.jpg
  inflating: /content/resized/UCM_497.jpg
  inflating: /content/resized/NWPU_10579.jpg
  inflating: /content/resized/NWPU_11575.jpg
  inflating: /content/resized/UCM_774.jpg
  inflating: /content/resized/NWPU_16383.jpg
  inflating: /content/resized/RSICD_1965.jpg
  inflating: /content/resized/NWPU_20383.jpg
  inflating: /content/resized/NWPU_17818.jpg
  inflating: /content/resized/NWPU_27126.jpg
  inflating: /content/resized/NWPU_7842.jpg
  inflating: /content/resized/NWPU_6765.jpg
  inflating: /content/resized/RSICD_9677.jpg
  inflating: /content/resized/NWPU_18959.jpg
  inflating: /content/resized/NWPU_11547.jpg
  inflating: /content/resized/NWPU_24496.jpg
  inflating: /content/resized/NWPU_26268.jpg
  inflating: /content/resized/NWPU_11216.jpg
  inflating: /content/resized/NWPU_2690.jpg
  inflating: /content/resized/NWPU_21812.jpg
  inflating: /content/resized/NWPU_21742.jpg
  inflating: /content/resized/RSICD_2626.jpg
  inflating: /content/resized/NWPU_5011.jpg
  inflating: /content/resized/RSICD_2221.jpg
  inflating: /content/resized/NWPU_28403.jpg
  inflating: /content/resized/UCM_393.jpg
  inflating: /content/resized/NWPU_6113.jpg
  inflating: /content/resized/RSICD_10125.jpg
  inflating: /content/resized/NWPU_3556.jpg
  inflating: /content/resized/NWPU_10320.jpg
  inflating: /content/resized/NWPU_29869.jpg
  inflating: /content/resized/RSICD_2154.jpg
  inflating: /content/resized/NWPU_18130.jpg
  inflating: /content/resized/NWPU_16096.jpg
  inflating: /content/resized/NWPU_5778.jpg
  inflating: /content/resized/RSICD_6985.jpg
  inflating: /content/resized/NWPU_22203.jpg
  inflating: /content/resized/NWPU_20453.jpg
  inflating: /content/resized/NWPU_8613.jpg
  inflating: /content/resized/RSICD_4897.jpg
  inflating: /content/resized/NWPU_19416.jpg
  inflating: /content/resized/NWPU_2688.jpg
  inflating: /content/resized/NWPU_30399.jpg
  inflating: /content/resized/NWPU_18993.jpg
  inflating: /content/resized/NWPU_21048.jpg

In [1]:
# Örnek: captions.csv'yi oku
import pandas as pd
df = pd.read_csv('captions.csv')
df.head()

,source,split,image,caption_1,caption_2,caption_3,caption_4,caption_5
0,NWPU,test,NWPU_31430.jpg,A gray plane on the runway and the lawn beside .,A grey plane is on the runway by the lawn .,There is an airplane on the runway with a larg...,A plane is parked on the runway next to the gr...,There is a plane on the runway beside the grass .
1,NWPU,test,NWPU_31431.jpg,Three small planes parked in a line on the air...,"There are four aircraft on the open ground, Th...",There are many planes of different sizes in a ...,Four planes are parked on the runway .,Four planes of different sizes were on the mar...
2,NWPU,test,NWPU_31432.jpg,A plane parked in a line on the airport with s...,A white plane was parked on the instruction li...,An airplane parked in an open area with many c...,A plane is parked on the open space .,There is 1 plane on the ground marked .
3,NWPU,test,NWPU_31433.jpg,A small plane and a big plane parked next to b...,A white plane and a gray plane parked at the b...,Two planes of different sizes are neatly parke...,A large plane and a small plane are parked nea...,Two planes are on the marked ground .
4,NWPU,test,NWPU_31434.jpg,Two planes parked next to boarding bridges .,Two aircraft were parked at the departure gates .,Two planes of different sizes are neatly parke...,Two planes are parked next to the terminal .,Two planes are on the marked ground .

In [4]:
!pip install huggingface_hub
!pip install evaluate transformers tqdm wandb
!pip install rouge_score
!pip install pycocoevalcap

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.11/dist-packages (0.32.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (2025.3.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (4.14.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (1.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub) (2025.4.26)
Collecting evaluate
  Downloading evaluate-0.4.3-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.52.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (4.67.1)
Requirement already satisfied: wandb in /usr/local/lib/python3.11/dist-packages (0.19.11)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.14.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.3.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.32.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from evaluate) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.70.15)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.2)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.32.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from evaluate) (24.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: click!=8.0.0,>=7.1 in /usr/local/lib/python3.11/dist-packages (from wandb) (8.2.1)
Requirement already satisfied: docker-pycreds>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from wandb) (0.4.0)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from wandb) (3.1.44)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.11/dist-packages (from wandb) (4.3.8)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<7,>=3.19.0 in /usr/local/lib/python3.11/dist-packages (from wandb) (5.29.5)
Requirement already satisfied: psutil>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from wandb) (5.9.5)
Requirement already satisfied: pydantic<3 in /usr/local/lib/python3.11/dist-packages (from wandb) (2.11.5)
Requirement already satisfied: sentry-sdk>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from wandb) (2.29.1)
Requirement already satisfied: setproctitle in /usr/local/lib/python3.11/dist-packages (from wandb) (1.3.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from wandb) (75.2.0)
Requirement already satisfied: typing-extensions<5,>=4.4 in /usr/local/lib/python3.11/dist-packages (from wandb) (4.14.0)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (3.11.15)
Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from docker-pycreds>=0.4.0->wandb) (1.17.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from gitpython!=3.1.29,>=1.0.0->wandb) (4.0.12)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.1.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3->wandb) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3->wandb) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3->wandb) (0.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2025.4.26)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.4.4)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.20.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb) (5.0.2)
Downloading evaluate-0.4.3-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 kB 8.8 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.3
Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: absl-py in /usr/local/lib/python3.11/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from rouge_score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.11/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk->rouge_score) (8.2.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk->rouge_score) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk->rouge_score) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from nltk->rouge_score) (4.67.1)
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=34c92bd4e8b3d6aaf72c7c2569aebf8811c7c48478c6408b090dfad40dab0a90
  Stored in directory: /root/.cache/pip/wheels/1e/19/43/8a442dc83660ca25e163e1bd1f89919284ab0d0c1475475148
Successfully built rouge_score
Installing collected packages: rouge_score
Successfully installed rouge_score-0.1.2
Collecting pycocoevalcap
  Downloading pycocoevalcap-1.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: pycocotools>=2.0.2 in /usr/local/lib/python3.11/dist-packages (from pycocoevalcap) (2.0.9)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from pycocotools>=2.0.2->pycocoevalcap) (2.0.2)
Downloading pycocoevalcap-1.2-py3-none-any.whl (104.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.3/104.3 MB 24.3 MB/s eta 0:00:00
Installing collected packages: pycocoevalcap
Successfully installed pycocoevalcap-1.2

In [2]:
from huggingface_hub import notebook_login
notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [3]:
import pandas as pd
import os
from sklearn.model_selection import train_test_split

train_df = df[df["split"] == "train"].copy()
val_df   = df[df["split"] == "val"].copy()
test_df  = df[df["split"] == "test"].copy()

# length evaluation
n_train = len(train_df)
n_val   = len(val_df)
n_test  = len(test_df)
total   = n_train + n_val + n_test

print(f"Train: {n_train} ({n_train/total:.2%})")
print(f"Test:  {n_test}  ({n_test/total:.2%})")
print(f"Val:   {n_val}   ({n_val/total:.2%})")

img_dir = '/content/resized'
all_images = set(os.listdir(img_dir))
df_images  = set(df['image'].unique())

missing = sorted(list(df_images - all_images))
if missing:
    print(f"Eksik {len(missing)} dosya var. Örnekler:", missing[:10])
else:
    print("Tüm caption’daki image isimleri klasörde bulundu.")

Train: 35614 (79.99%)
Test:  4454  (10.00%)
Val:   4453   (10.00%)
Tüm caption’daki image isimleri klasörde bulundu.

In [8]:
import os
import random
from PIL import Image
import wandb
import pandas as pd
import torch
from torch.utils.data import Dataset

from transformers import (
    PaliGemmaForConditionalGeneration,
    AutoProcessor,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    default_data_collator,
)
from peft import LoraConfig, get_peft_model, TaskType
import evaluate
from pycocoevalcap.cider.cider import Cider

# -------------------------------------------
# 0) WANDB oturumu
# -------------------------------------------
wandb.init(project="DI725_FinalProject", name="lora_r8_eos_post")

# -------------------------------------------
# 1) Model ve Processor Yükleme
# -------------------------------------------
model_name = "google/paligemma-3b-pt-224"
processor = AutoProcessor.from_pretrained(model_name, use_auth_token=True)
tokenizer = processor.tokenizer  # EOS token vs. için

base_model = PaliGemmaForConditionalGeneration.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.bfloat16,  # fp16 da olur ama bf16 daha stabil
    use_auth_token=True
)

# Dondurulmayacak kısımlar dışında her şey freeze
for param in base_model.vision_tower.parameters():
    param.requires_grad = False

for param in base_model.multi_modal_projector.parameters():
    param.requires_grad = False

# -------------------------------------------
# 2) Dinamik Caption Dataset
# -------------------------------------------
class RiscDynamicCaptionDataset(Dataset):
    def __init__(self, df, img_dir, processor, max_len=256):
        self.df = df.reset_index(drop=True)
        self.img_dir = img_dir
        self.proc = processor
        self.max_len = max_len

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img = Image.open(os.path.join(self.img_dir, row["image"])).convert("RGB")
        caps = [row[f"caption_{i}"] for i in range(1, 6)]
        cap = "<image> " + random.choice(caps) + tokenizer.eos_token

        enc = self.proc(
            images=img,
            text=cap,
            padding="max_length",
            truncation=True,
            max_length=self.max_len,
            return_tensors="pt"
        )

        return {
            "pixel_values": enc.pixel_values.squeeze(0),
            "input_ids": enc.input_ids.squeeze(0),
            "attention_mask": enc.attention_mask.squeeze(0),
            "labels": enc.input_ids.squeeze(0).clone()
        }

# -------------------------------------------
# 3) Train / Val Dataset’leri yükle
# -------------------------------------------
img_dir = "/content/resized"
train_ds = RiscDynamicCaptionDataset(train_df, img_dir, processor)
val_ds   = RiscDynamicCaptionDataset(val_df,   img_dir, processor)

# -------------------------------------------
# 4) LoRA Konfigürasyonu & PEFT Model
# -------------------------------------------
lora_cfg = LoraConfig(
    task_type=TaskType.SEQ_2_SEQ_LM,
    r=8,
    lora_alpha=16,
    lora_dropout=0.1,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
)
model_lora = get_peft_model(base_model, lora_cfg)
model_lora.print_trainable_parameters()

# -------------------------------------------
# 5) Eğitim Parametreleri & Trainer
# -------------------------------------------
training_args = Seq2SeqTrainingArguments(
    output_dir="lora_r8",
    per_device_train_batch_size=3,
    gradient_accumulation_steps=4,
    learning_rate=5e-5,
    num_train_epochs=1,
    logging_steps=5,
    eval_strategy="epoch",
    logging_strategy="steps",
    predict_with_generate=True,
    bf16=True,  # varsa bf16, yoksa fp16 kullanabilirsin
    push_to_hub=False,
    report_to="wandb",
    max_steps=1500
)

trainer = Seq2SeqTrainer(
    model=model_lora,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    data_collator=default_data_collator,
    tokenizer=processor
)

# -------------------------------------------
# 6) Eğitim & Değerlendirme
# -------------------------------------------
trainer.train()
lora_metrics = trainer.evaluate()
print("LoRA metrics:", lora_metrics)

# -------------------------------------------
# 7) Tahmin & Değerlendirme Metrikleri
# -------------------------------------------
raw_pred_ids = trainer.predict(val_ds).predictions
clean_preds = [tokenizer.decode(ids, skip_special_tokens=True).strip() for ids in raw_pred_ids]

references = val_df[[f"caption_{i}" for i in range(1,6)]].values.tolist()

# CIDEr
refs_dict  = {i: references[i] for i in range(len(references))}
preds_dict = {i: [clean_preds[i]] for i in range(len(clean_preds))}
cider_scorer = Cider()
cider_score, _ = cider_scorer.compute_score(refs_dict, preds_dict)

# BLEU, METEOR, ROUGE-L
bleu_res   = evaluate.load("bleu").compute(references=references, predictions=clean_preds)["bleu"]
meteor_res = evaluate.load("meteor").compute(references=references, predictions=clean_preds)["meteor"]
rouge_res  = evaluate.load("rouge").compute(references=references, predictions=clean_preds)["rougeL"]

print(f"BLEU:    {bleu_res:.4f}")
print(f"METEOR:  {meteor_res:.4f}")
print(f"ROUGE-L: {rouge_res:.4f}")
print(f"CIDEr:   {cider_score:.4f}")

wandb.log({
    "bleu":   bleu_res,
    "meteor": meteor_res,
    "rougeL": rouge_res,
    "cider":  cider_score
})

# -------------------------------------------
# 8) CSV ve WandB için örnek kayıt
# -------------------------------------------
rows = []
for i, img_name in enumerate(val_ds.df["image"].tolist()):
    row = {"image": img_name, "pred": clean_preds[i]}
    for j, r in enumerate(references[i], start=1):
        row[f"ref_{j}"] = r
    rows.append(row)
pd.DataFrame(rows).to_csv("lora_r8_eos_post_val_results.csv", index=False)
print("Saved CSV → lora_r8_eos_post_val_results.csv")

table = wandb.Table(columns=["image", "prediction", "references"])
for idx in random.sample(range(len(clean_preds)), 5):
    table.add_data(val_ds.df["image"].iloc[idx],
                   clean_preds[idx],
                   " || ".join(references[idx]))
wandb.log({"examples": table})

/usr/local/lib/python3.11/dist-packages/transformers/models/auto/processing_auto.py:255: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(

preprocessor_config.json:   0%|          | 0.00/699 [00:00<?, ?B/s]

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.

tokenizer_config.json:   0%|          | 0.00/40.0k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.26M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/24.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/607 [00:00<?, ?B/s]

/usr/local/lib/python3.11/dist-packages/transformers/modeling_utils.py:4191: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(

config.json:   0%|          | 0.00/1.03k [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/62.6k [00:00<?, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/1.74G [00:00<?, ?B/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/4.95G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

<ipython-input-8-2377845188>:120: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(
No label_names provided for model class `PeftModelForSeq2SeqLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

trainable params: 11,298,816 || all params: 2,934,765,296 || trainable%: 0.3850

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
`loss_type=None` was set in the config but it is unrecognised.Using the default loss: `ForCausalLMLoss`.

LoRA metrics: {'eval_loss': 13.111368179321289, 'eval_runtime': 254.5174, 'eval_samples_per_second': 17.496, 'eval_steps_per_second': 2.188, 'epoch': 0.5053908355795148}

Downloading builder script:   0%|          | 0.00/5.94k [00:00<?, ?B/s]

Downloading extra modules:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

Downloading extra modules:   0%|          | 0.00/3.34k [00:00<?, ?B/s]

Downloading builder script:   0%|          | 0.00/7.02k [00:00<?, ?B/s]

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

Downloading builder script:   0%|          | 0.00/6.27k [00:00<?, ?B/s]

BLEU:    0.0000
METEOR:  0.0000
ROUGE-L: 0.0000
CIDEr:   0.0000
Saved CSV → lora_r8_eos_post_val_results.csv

In [4]:
!pip install -q -U bitsandbytes

In [5]:
!pip install -q -U transformers datasets peft bitsandbytes

In [6]:
import requests
from transformers import AutoProcessor, PaliGemmaForConditionalGeneration
import requests
from datasets import load_dataset
from peft import get_peft_model, LoraConfig
from transformers import BitsAndBytesConfig
from transformers import AutoProcessor, PaliGemmaForConditionalGeneration

In [37]:
import os
import io
import random
import pandas as pd
import wandb
import torch
from PIL import Image
from datasets import Dataset
from transformers import (
    PaliGemmaProcessor,
    PaliGemmaForConditionalGeneration,
    Trainer,
    TrainingArguments,
    BitsAndBytesConfig
)
from peft import LoraConfig, get_peft_model
import evaluate
from pycocoevalcap.cider.cider import Cider

# 0) WANDB oturumu
wandb.init(project="DI725_FinalProject", name="finetuned_paligemma")

# 1) Yardımcı: HF image‐feature → PIL dönüşümü
def to_pil(img):
    if isinstance(img, Image.Image):
        return img
    elif isinstance(img, dict) and img.get("path"):
        return Image.open(img["path"]).convert("RGB")
    elif isinstance(img, dict) and img.get("bytes"):
        return Image.open(io.BytesIO(img["bytes"])).convert("RGB")
    else:
        # numpy array vb.
        return Image.fromarray(img).convert("RGB")

# 2) Veriyi oku ve HF Dataset nesnesine dönüştür
df = pd.read_csv("captions.csv")
train_df = df[df["split"] == "train"].reset_index(drop=True)
val_df   = df[df["split"] == "val"].reset_index(drop=True)

def df_to_dataset(df):
    def load_image(example):
        example["image_id"] = example["image"]
        example["image"] = {"path": os.path.join("/content/resized", example["image"])}
        return example

    ds = Dataset.from_pandas(df)
    return ds.map(load_image)

train_ds = df_to_dataset(train_df)
val_ds   = df_to_dataset(val_df)

# 3) Processor ve model
model_id  = "google/paligemma-3b-pt-224"
processor = PaliGemmaProcessor.from_pretrained(model_id)

def collate_fn(examples):
    images, texts = [], []
    for ex in examples:
        pil = to_pil(ex["image"])
        images.append(pil)
        texts.append(f"<image> <bos> describe this image. {ex['caption_1']}")
    batch = processor(
        images=images,
        text=texts,
        return_tensors="pt",
        padding="longest",
        truncation=True
    )
    # Trainer’ın internal loss hesabı için labels ekle
    batch["labels"] = batch["input_ids"].clone()
    return batch

# 4) Model & LoRA
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)
base_model = PaliGemmaForConditionalGeneration.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto"
)
lora_config = LoraConfig(
    r=8,
    target_modules=["q_proj","k_proj","v_proj","o_proj","up_proj","down_proj","gate_proj"],
    task_type="CAUSAL_LM"
)
model = get_peft_model(base_model, lora_config)
model.print_trainable_parameters()

# 5) Eğitim argümanları
args = TrainingArguments(
    output_dir="finetuned_paligemma_riscm_yourdata",
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    learning_rate=2e-5,
    num_train_epochs=1,
    dataloader_pin_memory=False,
    bf16=True,
    logging_steps=10,
    max_steps=500,
    save_strategy="epoch",
    report_to="wandb",
    remove_unused_columns=False,
    dataloader_num_workers=8
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    data_collator=collate_fn
)

# 6) Eğitim
trainer.train()

from time import time
from tqdm.auto import tqdm
import math
import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.allow_tf32   = True

# 1) Prepare model for fast generation
model.eval()
model.gradient_checkpointing_disable()   # re-enable use_cache

# 2) Inference in mini-batches with ETA
clean_preds, references = [], []
batch_size = 32
total_batches = math.ceil(len(val_ds) / batch_size)

pbar = tqdm(total=total_batches, desc="Generating", unit="batch")

for batch_idx in range(0, len(val_ds), batch_size):
    start_time = time()

    # select a true Dataset slice
    batch = val_ds.select(range(batch_idx, min(batch_idx+batch_size, len(val_ds))))
    images = [to_pil(ex["image"]) for ex in batch]
    refs   = [[ex[f"caption_{j}"] for j in range(1,6)] for ex in batch]
    prompts = ["<image> <bos> describe this image."] * len(images)

    inputs = processor(
        text=prompts,
        images=images,
        return_tensors="pt",
        padding="longest",
        truncation=True
    ).to("cuda")

    gen_ids = model.generate(**inputs, max_new_tokens=64)
    texts   = processor.tokenizer.batch_decode(gen_ids, skip_special_tokens=True)

    # record
    clean_preds.extend([t.strip() for t in texts])
    references.extend(refs)

    # update progress bar
    batch_time = time() - start_time
    pbar.update(1)
    pbar.set_postfix({"last_batch_s": f"{batch_time:.1f}"})

pbar.close()

# 3) Compute metrics (same as before)
refs_dict  = {i: references[i]    for i in range(len(references))}
preds_dict = {i: [clean_preds[i]] for i in range(len(clean_preds))}
cider_scorer = Cider()
cider_score, _ = cider_scorer.compute_score(refs_dict, preds_dict)

bleu   = evaluate.load("bleu"  ).compute(predictions=clean_preds, references=references)["bleu"]
meteor = evaluate.load("meteor").compute(predictions=clean_preds, references=references)["meteor"]
rouge  = evaluate.load("rouge" ).compute(predictions=clean_preds, references=references)["rougeL"]

metrics = {
    "eval/bleu":   bleu,
    "eval/meteor": meteor,
    "eval/rougeL": rouge,
    "eval/cider":  cider_score,
}
print(metrics)
wandb.log(metrics)

# 4) Save to CSV (same as before)
rows = []
for i, ex in enumerate(val_df.itertuples(index=False)):
    row = {"image": ex.image, "pred": clean_preds[i]}
    for j in range(1,6):
        row[f"ref_{j}"] = getattr(ex, f"caption_{j}")
    rows.append(row)
pd.DataFrame(rows).to_csv("inference_results.csv", index=False)

Map:   0%|          | 0/35614 [00:00<?, ? examples/s]

Map:   0%|          | 0/4453 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

trainable params: 11,298,816 || all params: 2,934,765,296 || trainable%: 0.3850

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

Generating:   0%|          | 0/140 [00:00<?, ?batch/s]

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

{'eval/bleu': 0.0, 'eval/meteor': np.float64(0.06911412588396391), 'eval/rougeL': np.float64(0.03238544158177521), 'eval/cider': np.float64(0.0009708322805579115)}

In [45]:
import os
import io
import random
import pandas as pd
import wandb
import torch
from PIL import Image
from datasets import Dataset
from transformers import (
    PaliGemmaProcessor,
    PaliGemmaForConditionalGeneration,
    Trainer,
    TrainingArguments,
    BitsAndBytesConfig
)
from peft import LoraConfig, get_peft_model
import evaluate
from pycocoevalcap.cider.cider import Cider

# 0) WANDB oturumu
wandb.init(project="DI725_FinalProject", name="finetuned_paligemma")

# 1) Yardımcı: HF image‐feature → PIL dönüşümü
def to_pil(img):
    if isinstance(img, Image.Image):
        return img
    elif isinstance(img, dict) and img.get("path"):
        return Image.open(img["path"]).convert("RGB")
    elif isinstance(img, dict) and img.get("bytes"):
        return Image.open(io.BytesIO(img["bytes"])).convert("RGB")
    else:
        # numpy array vb.
        return Image.fromarray(img).convert("RGB")

# 2) Veriyi oku ve HF Dataset nesnesine dönüştür
df = pd.read_csv("captions.csv")
train_df = df[df["split"] == "train"].reset_index(drop=True)
val_df   = df[df["split"] == "val"].reset_index(drop=True)

def df_to_dataset(df):
    def load_image(example):
        example["image_id"] = example["image"]
        example["image"] = {"path": os.path.join("/content/resized", example["image"])}
        return example

    ds = Dataset.from_pandas(df)
    return ds.map(load_image)

train_ds = df_to_dataset(train_df)
val_ds   = df_to_dataset(val_df)

# 3) Processor ve model
model_id  = "google/paligemma-3b-pt-224"
processor = PaliGemmaProcessor.from_pretrained(model_id)

def collate_fn(examples):
    # 1) Görselleri PIL→RGB
    images  = [ to_pil(ex["image"]) for ex in examples ]
    # 2) Prompt’u hazırla
    prompts = ["<image> <bos> describe this image."] * len(examples)
    # 3) Hedef caption’ları al
    captions = [ ex["caption_1"] for ex in examples ]

    # 4) Tek çağrıda hem input_ids hem suffix (yani labels) oluştur
    batch = processor(
        text=prompts,
        images=images,
        suffix=captions,            # burası hedef label’ı veriyor
        return_tensors="pt",
        padding="longest",
        truncation=True
    )

    # 5) Pad token’ları -100 ile maskele (Trainer kayıpta bunları görmezden gelir)
    labels = batch["labels"].clone()
    labels[labels == processor.tokenizer.pad_token_id] = -100
    batch["labels"] = labels

    return batch

    # Trainer’ın internal loss hesabı için labels ekle
    batch["labels"] = batch["input_ids"].clone()
    return batch

# 4) Model & LoRA
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)
base_model = PaliGemmaForConditionalGeneration.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto"
)
lora_config = LoraConfig(
    r=8,
    target_modules=["q_proj","k_proj","v_proj","o_proj","up_proj","down_proj","gate_proj"],
    task_type="CAUSAL_LM"
)
model = get_peft_model(base_model, lora_config)
model.print_trainable_parameters()

# 5) Eğitim argümanları
args = TrainingArguments(
    output_dir="finetuned_paligemma_riscm_yourdata",
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    learning_rate=2e-5,
    num_train_epochs=1,
    dataloader_pin_memory=False,
    bf16=True,
    logging_steps=10,
    max_steps=500,
    save_strategy="epoch",
    report_to="wandb",
    remove_unused_columns=False,
    dataloader_num_workers=8
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    data_collator=collate_fn
)

# 6) Eğitim
trainer.train()

from time import time
from tqdm.auto import tqdm
import math
import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.allow_tf32   = True

# 1) Prepare model for fast generation
model.eval()
model.gradient_checkpointing_disable()   # re-enable use_cache

# 2) Inference in mini-batches with ETA
clean_preds, references = [], []
batch_size = 32
total_batches = math.ceil(len(val_ds) / batch_size)

pbar = tqdm(total=total_batches, desc="Generating", unit="batch")

for batch_idx in range(0, len(val_ds), batch_size):
    start_time = time()

    # select a true Dataset slice
    batch = val_ds.select(range(batch_idx, min(batch_idx+batch_size, len(val_ds))))
    images = [to_pil(ex["image"]) for ex in batch]
    refs   = [[ex[f"caption_{j}"] for j in range(1,6)] for ex in batch]
    prompts = ["<image> <bos> describe this image."] * len(images)

    inputs = processor(
        text=prompts,
        images=images,
        return_tensors="pt",
        padding="longest",
        truncation=True
    ).to("cuda")

    gen_ids = model.generate(**inputs, max_new_tokens=64)
    texts   = processor.tokenizer.batch_decode(gen_ids, skip_special_tokens=True)

    # record
    clean_preds.extend([t.strip() for t in texts])
    references.extend(refs)

    # update progress bar
    batch_time = time() - start_time
    pbar.update(1)
    pbar.set_postfix({"last_batch_s": f"{batch_time:.1f}"})

pbar.close()

# 3) Compute metrics (same as before)
refs_dict  = {i: references[i]    for i in range(len(references))}
preds_dict = {i: [clean_preds[i]] for i in range(len(clean_preds))}
cider_scorer = Cider()
cider_score, _ = cider_scorer.compute_score(refs_dict, preds_dict)

bleu   = evaluate.load("bleu"  ).compute(predictions=clean_preds, references=references)["bleu"]
meteor = evaluate.load("meteor").compute(predictions=clean_preds, references=references)["meteor"]
rouge  = evaluate.load("rouge" ).compute(predictions=clean_preds, references=references)["rougeL"]

metrics = {
    "eval/bleu":   bleu,
    "eval/meteor": meteor,
    "eval/rougeL": rouge,
    "eval/cider":  cider_score,
}
print(metrics)
wandb.log(metrics)

# 4) Save to CSV (same as before)
rows = []
for i, ex in enumerate(val_df.itertuples(index=False)):
    row = {"image": ex.image, "pred": clean_preds[i]}
    for j in range(1,6):
        row[f"ref_{j}"] = getattr(ex, f"caption_{j}")
    rows.append(row)
pd.DataFrame(rows).to_csv("inference_results.csv", index=False)

Map:   0%|          | 0/35614 [00:00<?, ? examples/s]

Map:   0%|          | 0/4453 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

trainable params: 11,298,816 || all params: 2,934,765,296 || trainable%: 0.3850

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

NameError: Caught NameError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py", line 349, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "<ipython-input-45-2895344672>", line 65, in collate_fn
    batch = processor(
            ^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/processing_paligemma.py", line 313, in __call__
    labels = np.array(inputs["input_ids"])
             ^^
NameError: name 'np' is not defined